## Subir al servidor
POST http://localhost:4000/api/v1/users HTTP/1.1
Content-Type: application/json

{
  "name": "Alex_2",
  "username": "Xalex79_2",
  "email": "example2@test.com"
}

### Recoger todo del servidor
GET http://localhost:4000/api/v1/users/ HTTP/1.1

### Recoger especifico por _id del servidor
GET http://localhost:4000/api/v1/users/66fb071ea7b17758a1b21db0 HTTP/1.1

### Actualizar algun campo de dato (por _id) del servidor
PUT http://localhost:4000/api/v1/users/66fb071ea7b17758a1b21db0 HTTP/1.1
Content-Type: application/json

{
  "name": "Alex_3"
  //"username": "Xalex79_2",
  //"email": "example2@test.com"
}

### Eliminar del servidor por _id
DELETE http://localhost:4000/api/v1/users/66fb070aa7b17758a1b21dae HTTP/1.1

//DELETE http://localhost:4000/api/v1/users/<_ID AQUI> HTTP/1.1
